/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f103xx.h"

void delay_ms(uint32_t ms);

int main(void)
{
    /* enable clock for port A and B*/
	GPIOA_PCLK_EN();
	GPIOB_PCLK_EN();

	/* clear bits in CRL*/
	GPIOA->CRL &= ~(0xFFF << (4*5));

	/* set MODE=01 CNF=00 for pins A5, A6, A7 */
	GPIOA->CRL |= (0x111 << (4*5));

	GPIOB->CRL &= ~(0xF << 0);  /* clear bits */
	GPIOB->CRL |=  (0x8 << 0);  /*CNF0 =10 MODE0=00 for input configuration */
	GPIOB->ODR &=  ~(1   << 0);  /*ODR0=0 to activate pull down */

	while(1)
	{
		GPIOA->ODR |= (1<<7);  /*A7 green light is on */

		if( (GPIOB->IDR & (1<<0)) != 0)
		{
			GPIOA->ODR &= ~(1<<7);  /* turn green light off*/

			GPIOA->ODR |= (1<<6);   /* yellow light is on for 2s*/
			delay_ms(2000);
			GPIOA->ODR &= ~(1<<6);  /* yellow off*/

			GPIOA->ODR |= (1<<5);   /*red light is on for 5s*/
			delay_ms(5000);
			GPIOA->ODR &= ~(1<<5);  /*red off*/

		}

	}

}
void delay_ms(uint32_t ms)
{
    for(uint32_t i = 0; i < ms * 1000; i++)
    {
        __asm__("nop"); // one CPU no-operation instruction
    }
}
